const config = require('./config.json')
const Telegraf = require('telegraf')
const bot = new Telegraf(config.bot_token)
bot.start((ctx) => ctx.reply('Welcome!'))
bot.dating( (ctx) => ctx.reply("Привіт! Розпочнемо раунд speed-dating'у? \nРеєстрація триватиме 2 хвилини (120 сек)"))
bot.help((ctx) => ctx.reply('Send me a sticker'))
bot.on('sticker', (ctx) => ctx.reply('👍'))
bot.hears('hi', (ctx) => ctx.reply('Hey there'))
bot.launch()